/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author sdc-daniel
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLValor01 = new javax.swing.JLabel();
        jLValor02 = new javax.swing.JLabel();
        jTValor01 = new javax.swing.JTextField();
        jTValor02 = new javax.swing.JTextField();
        jBCalcular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRSoma = new javax.swing.JRadioButton();
        jRSubtracao = new javax.swing.JRadioButton();
        jRDivisao = new javax.swing.JRadioButton();
        jRMultiplicao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLValor01.setText("Valor01:");

        jLValor02.setText("Valor02:");

        jBCalcular.setText("Calcular");
        jBCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBCalcularMouseClicked(evt);
            }
        });

        buttonGroup1.add(jRSoma);
        jRSoma.setText("Soma");

        buttonGroup1.add(jRSubtracao);
        jRSubtracao.setText("Subtracao");

        buttonGroup1.add(jRDivisao);
        jRDivisao.setText("Divisao");

        buttonGroup1.add(jRMultiplicao);
        jRMultiplicao.setText("Multiplicacao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRMultiplicao)
                    .addComponent(jRSoma, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRSubtracao, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRDivisao, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRSubtracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jRDivisao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRMultiplicao)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLValor01)
                            .addComponent(jLValor02))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTValor01, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jTValor02)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jBCalcular)))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLValor01)
                            .addComponent(jTValor01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLValor02)
                            .addComponent(jTValor02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBCalcular)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBCalcularMouseClicked
        // TODO add your handling code here:
        if(jTValor01.getText().isEmpty() || jTValor02.getText().isEmpty())
        {
             JOptionPane.showMessageDialog(rootPane, "Por favor insira um valor");           
        }
        else
        {
        val01 = Double.parseDouble(jTValor01.getText());
        val02 = Double.parseDouble(jTValor02.getText());
        }
//        resultado = val01 + val02;
        if(jRSoma.isSelected())
        {
            resultado = gen.Soma(val01, val02);  
            JOptionPane.showMessageDialog(rootPane, "Valor Calculado:"+resultado.toString());
        }
        else if(jRSubtracao.isSelected())
        {
            resultado = gen.Subtracao(val01, val02);  
            JOptionPane.showMessageDialog(rootPane, "Valor Calculado:"+resultado.toString());
        }
        else if(jRMultiplicao.isSelected())
        {
            resultado = gen.Multiplicacao(val01, val02);  
            JOptionPane.showMessageDialog(rootPane, "Valor Calculado:"+resultado.toString());
        }
        else if(jRDivisao.isSelected())
        {
            resultado = gen.Divisao(val01, val02);  
            JOptionPane.showMessageDialog(rootPane, "Valor Calculado:"+resultado.toString());
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Selecione umas das operacoes!");

    }//GEN-LAST:event_jBCalcularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    Operacoes gen = new Operacoes();
    private Double resultado, val01,val02;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCalcular;
    private javax.swing.JLabel jLValor01;
    private javax.swing.JLabel jLValor02;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRDivisao;
    private javax.swing.JRadioButton jRMultiplicao;
    private javax.swing.JRadioButton jRSoma;
    private javax.swing.JRadioButton jRSubtracao;
    private javax.swing.JTextField jTValor01;
    private javax.swing.JTextField jTValor02;
    // End of variables declaration//GEN-END:variables
}
